masite/urls.py
from django.contrib import admin
from django.urls import include, path

from mediaanalytics import errorViews
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mediaanalytics.urls')),
    path('admin/', admin.site.urls),
]
handler404 = errorViews.error404
handler500 = errorViews.error500

mediaanalytics/urls.py
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'mediaanalytics'
urlpatterns = [
    # Views URLS
    path('', views.home, name='home'),
    path('article/', views.output, name='output'),
    path('timeline/', views.timeline, name='timeline'),
    path('nlp/', views.nlp, name='nlp'),
    path('about/', views.about, name='about'),
    path('article/<int:article_id>/', views.display, name='article'),
    
    # API URLS
    # POST requests
    path('api/articles/find/', views.getOvertime, name='articlesAPI'),
    path('api/articles/topwords/', views.getTopWords, name='getTopWords'),
    path('api/articles/similar/', views.getSimilarWords, name='getSimilarWords'),
    path('api/articles/notmatch/', views.getNotMatch, name='getNotMatch'),
    path('api/articles/similarity/', views.getSimilarity, name='getSimilarity'),
    path('api/articles/word/', views.getSpecificWord, name='getSpecificWord'),
    path('api/articles/xyz/', views.getAnalogies, name='getAnalogies'),
    # GET requests
    path('api/articles/find/<int:year1>/<int:year2>/<str:word>/', views.getOvertime, name='articlesAPI'),
    path('api/articles/similar/<int:yearID>/<str:wordToFind>/', views.getSimilarWords, name='getSimilarWords'),
    path('api/articles/topwords/<int:yearID>/', views.getTopWords, name='getTopWords'),
    path('api/articles/topwords/<int:yearID>/<int:breakID>/', views.getTopWords, name='getTopWords'),
    path('api/articles/similarity/<int:yearID>/<str:word1>/<str:word2>/', views.getSimilarity, name='getSimilarity'),
    path('api/articles/word/<int:yearID>/<str:word>/', views.getSpecificWord, name='getSpecificWord'),
    path('img/tsne/<int:yearID>/<str:words>/', views.getTSNE, name='getTSNE')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mediaanalytics/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.TextField(null=True)
    text = models.TextField(null=True)
    author = models.TextField(null=True)
    date = models.DateField(null=True)
    section = models.TextField(null=True)
    url = models.TextField(null=True)

mediaanalytics/forms.py
from django import forms

class SearchForm(forms.Form):
    keyword = forms.CharField(label='Search here', required=False)

mediaanalytics/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Q, Count

from django.contrib import messages

from .models import *
from .api import *

# View for displaying the home page
@csrf_exempt
def home(request):
    context = {}
    context["years"] = yearRange()
    context["sections"] = Article.objects.raw('SELECT 1 as id, section FROM mediaanalytics_article GROUP by section ORDER by section')
    context["authors"] = Article.objects.raw('SELECT 1 as id, author FROM mediaanalytics_article GROUP by author ORDER by author')
    return render(request, 'sitepages/home.html', context)

# View for displaying the graph page
@csrf_exempt
def timeline(request):
    context = {}
    context["years"] = yearRange()
    if request.method == 'POST':
        if request.POST.get("word") != "":
            headerText = ""
            listInput = convertToList(request.POST.get("word"))
            year1 = request.POST.get("year1")
            year2 = request.POST.get("year2")
            # If the user selects both years from the timeline page it would display the timeline for the years in between
            if year1 !="" and year2 !="":
                if int(year1) > int(year2):
                    year1, year2 = year2, year1
                context['year1'] = year1
                context['year2'] = year2
            elif year1 !="":
                context['year1'] = year1
                context['year2'] = yearEnd
            elif year2 !="":
                context['year1'] = yearStart
                context['year2'] = year2
            else:
                #Otherwise it would display the years from yearStart and yearEnd from the loadModels.py file
                context['year1'] = yearStart
                context['year2'] = yearEnd
            if len(listInput) == 1:
                if context['year1']==context['year2']:
                    headerText = "<small>Time series of </small> "+ request.POST.get("word") +" <small>in</small> "+ str(context['year1'])
                else:
                    headerText = "<small>Time series of </small> "+ request.POST.get("word") +" <small>between</small> "+ str(context['year1']) +" <small>and</small> " + str(context['year2'])
            else:
                if context['year1']==context['year2']:
                    headerText = "<small>Time series of words in</small>  "+ str(context['year1'])
                else:
                    headerText = "<small>Time series of words between</small>  "+ str(context['year1']) +" <small>and</small> " + str(context['year2'])
            context['headerText'] = headerText
            if len(listInput) == 1:
                context['word'] = listInput[0]
                return render(request, 'sitepages/timeline/output.html', context)
            else:
                context['words'] = listInput
                return render(request, 'sitepages/timeline/output2.html', context)
    return render(request, 'sitepages/timeline/search.html', context)

# View for displaying the output page
@csrf_exempt
def output(request):
    context = {}
    # Fetches all the articles from the model
    articles = Article.objects.all()
    context['headerText'] = "All articles "
    #If the request is POST
    if request.method == 'POST':
        # If the articleText request is not blank it filters the text to the articles text
        if request.POST.get("articleText") != "":
            articles = articles.filter(Q(text__contains=request.POST['articleText']) | Q(title__contains=request.POST['articleText']))
            context['headerText'] = "Results for " + request.POST.get("articleText")
        # If the year is selected not empty, it filters the date by the year selected
        if request.POST.get("year") != "":
            articles = articles.filter(date__year=request.POST.get("year"))
            context['headerText'] += " in " + request.POST.get("year")
        if request.POST.get("author") != "":
            articles = articles.filter(author=request.POST.get("author"))
            context['headerText'] += " by " + request.POST.get("author")
        if request.POST.get("section") != "":
            articles = articles.filter(section=request.POST.get("section"))
            context['headerText'] += " that are " + request.POST.get("section")

    # Sets the articles context to the articles model
    context['articles'] = articles
    return render(request, 'sitepages/output.html', context)  

# View for displaying the display article page
def display(request, article_id):
    context = {}
    article = get_object_or_404(Article, id=article_id)
    context['article'] = article
    return render(request, 'sitepages/article.html', context)

@csrf_exempt
def nlp(request):
    context = {}
    context["years"] = yearRange()
    if request.method == 'POST':
        # If the first year is not selected it returns back to the NLP home page
        if request.POST.get("year1") !="":
            emptyFields = True
            # GETS ALL THE INFORMATION FROM THE NLP SEARCH PAGE (nlp/search.html)
            context["year1"] = request.POST.get("year1")
            # If the first year is not selected it returns back to the NLP home page
            if request.POST.get("topWordsBreak") !="":
                if request.POST.get("topWordsBreak").isdigit():
                    emptyFields = False
                    context["topWordsBreak"] = request.POST.get("topWordsBreak")
                else:
                    messages.error(request, "ERROR: Top words must be a numeric value")
                    return redirect('mediaanalytics:nlp')
            if request.POST.get("oddOneOut") !="":
                emptyFields = False
                context["oddOneOut"] = request.POST.get("oddOneOut")
            if request.POST.get("ranking") !="":
                emptyFields = False
                context["ranking"] = request.POST.get("ranking")
            if request.POST.get("year2") !="":
                context["year2"] = request.POST.get("year2")
                if int(context["year2"]) == int(context["year1"]):
                    context["year2"] = None
            if request.POST.get("similarWord1") !="" and request.POST.get("similarWord2") !="":
                emptyFields = False
                context["similarity1"] = request.POST.get("similarWord1")
                context["similarity2"] = request.POST.get("similarWord2")
            if request.POST.get("similarWord") !="":
                emptyFields = False
                context["similarWord"] = request.POST.get("similarWord")
            if request.POST.get("ranking") !="":
                emptyFields = False
                context["ranking"] = request.POST.get("ranking")
            if request.POST.get("analogy-x") !="" and request.POST.get("analogy-y") !="" and request.POST.get("analogy-z") !="":
                emptyFields = False
                context["analogyX"] = request.POST.get("analogy-x")
                context["analogyY"] = request.POST.get("analogy-y")
                context["analogyZ"] = request.POST.get("analogy-z")
            if request.POST.get("tnse") !="":
                emptyFields = False
                context["tnse"] = request.POST.get("tnse")
            if emptyFields == True:
                messages.error(request, "ERROR: Must select something below")
                return redirect('mediaanalytics:nlp')
            return render(request, 'sitepages/nlp/output.html', context)
        else:
            messages.error(request, "ERROR: Must select a year")
            return redirect('mediaanalytics:nlp')
    return render(request, 'sitepages/nlp/search.html', context)

def about(request):
    return render(request, 'sitepages/about.html')

# Function that returns the year array from yearStart and yearEnd from the loadModels.py file
def yearRange():
    yearsArray = []
    for i in range(yearStart, yearEnd+1):
        yearsArray.append(i)
    return yearsArray

mediaanalytics/templates/sitepages/timeline/output.html
{% extends "layout.html" %}
{% block title %}Time series of {{word}}{% endblock %}
{% load static %}
{% block content %} 
<div class="search">
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="{% static 'js/graph.js'%}"></script>

<h1 class="my-4">{{headerText|safe}}</h1>

<p>Hover over the dots for details of the word</p>
<p id="p1">Loading...</p>

<script>
var textInput = "{{ word }}";
var y1Input = "{{ year1 }}";
var y2Input = "{{ year2 }}";
var context = {word:textInput, yearFrom:y1Input, yearTo:y2Input};
$.post("{% url 'mediaanalytics:articlesAPI' %}", context, function(response) {
    if (response.code == 1) {
        document.getElementById("p1").innerHTML = "";
        var api = response.word;
        d3.select("svg").remove();
        drawGraph(api);
    } 
    else 
    {
        document.getElementById("p1").innerHTML = "API not found";
    }
});
</script>
</div>
{% endblock %}

mediaanalytics/templates/sitepages/timeline/output2.html
{% extends "layout.html" %}
{% block title %}Time series of words{% endblock %}
{% load static %}
{% block content %} 
<div class="search">
<h1 class="my-4">{{headerText|safe}}</h1>

<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="{% static 'js/graph.js'%}"></script>

<div class="row">
{% for word in words %}
	<div class="col-lg-6 col-sm-6 portfolio-item">
		<div class="card h-100">
			<div class="card-body">
				<h4 class="card-title">{{ word }}</h4>
                <div id="card-{{word}}"></div>
                <form action="{% url 'mediaanalytics:timeline'%}" method="post" target="_blank">
                <input type="hidden" id="word" name="word" value="{{ word }}">
                <input type="hidden" id="year1" name="year1" value="{{ year1 }}">
                <input type="hidden" id="year2" name="year2" value="{{ year2 }}">
                <input type="submit" class="button2" value="Open timeline in new window" />
                </form>
			</div>
		</div>
	</div>
{% endfor %}
<div class="row">

<script>
    var y1Input = "{{ year1 }}";
    var y2Input = "{{ year2 }}";
{% for word in words %}
    var textInput = "{{ word }}";
    var context = {word:textInput, yearFrom:y1Input, yearTo:y2Input};
    $.post("{% url 'mediaanalytics:articlesAPI' %}", context, function(response) {
        if (response.code == 1) {
            var api = response.word;
            drawGraph2(api, "#card-{{word}}");
        } 
        else 
        {
        }
    });
{% endfor %}
</script>

</div>

</div>
{% endblock %}

mediaanalytics/templates/sitepages/timeline/search.html
{% extends "layout.html" %}
{% block title %}Timeline{% endblock %}
{% block content %} 
<div class="my-4 search">
	<h1 class="my-4">Timeline</h1>
	Select time series between two years below:<br>(Leave blank for a time series between 1975 and 2017)

	<form action="{% url 'mediaanalytics:timeline' %}" method=post class=add-entry>
		
	<select name="year1" class="colwidthTwentyFive shadow">
        <option value="">Select year</option>
        {% for year in years %}
        <option value="{{ year }}">{{ year }}</option>
	    {% endfor %}
    </select>

    <select name="year2" class="colwidthTwentyFive shadow">
        <option value="">Select another year</option>
        {% for year in years %}
        <option value="{{ year }}">{{ year }}</option>
	    {% endfor %}
    </select>
	<p></p>
	Search word for a time series:
	<br>
	<input type="text" name="word" class="colwidthFifty shadow" placeholder="You can also check for multiple words by seperating them by commas" required>
	<p></p>
    <input type="submit" class="button" value="Search" name="submitWord">
	</form>
</div>
{% endblock %}