masite/urls.py
from django.contrib import admin
from django.urls import include, path

from mediaanalytics import errorViews
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mediaanalytics.urls')),
    path('admin/', admin.site.urls),
]
handler404 = errorViews.error404
handler500 = errorViews.error500

mediaanalytics/urls.py
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'mediaanalytics'
urlpatterns = [
    # Views URLS
    path('', views.home, name='home'),
    path('article/', views.output, name='output'),
    path('timeline/', views.timeline, name='timeline'),
    path('nlp/', views.nlp, name='nlp'),
    path('about/', views.about, name='about'),
    path('article/<int:article_id>/', views.display, name='article'),
    
    # API URLS
    # POST requests
    path('api/articles/find/', views.getOvertime, name='articlesAPI'),
    path('api/articles/topwords/', views.getTopWords, name='getTopWords'),
    path('api/articles/similar/', views.getSimilarWords, name='getSimilarWords'),
    path('api/articles/notmatch/', views.getNotMatch, name='getNotMatch'),
    path('api/articles/similarity/', views.getSimilarity, name='getSimilarity'),
    path('api/articles/word/', views.getSpecificWord, name='getSpecificWord'),
    path('api/articles/xyz/', views.getAnalogies, name='getAnalogies'),
    # GET requests
    path('api/articles/find/<int:year1>/<int:year2>/<str:word>/', views.getOvertime, name='articlesAPI'),
    path('api/articles/similar/<int:yearID>/<str:wordToFind>/', views.getSimilarWords, name='getSimilarWords'),
    path('api/articles/topwords/<int:yearID>/', views.getTopWords, name='getTopWords'),
    path('api/articles/topwords/<int:yearID>/<int:breakID>/', views.getTopWords, name='getTopWords'),
    path('api/articles/similarity/<int:yearID>/<str:word1>/<str:word2>/', views.getSimilarity, name='getSimilarity'),
    path('api/articles/word/<int:yearID>/<str:word>/', views.getSpecificWord, name='getSpecificWord'),
    path('img/tsne/<int:yearID>/<str:words>/', views.getTSNE, name='getTSNE')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mediaanalytics/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.TextField(null=True)
    text = models.TextField(null=True)
    author = models.TextField(null=True)
    date = models.DateField(null=True)
    section = models.TextField(null=True)
    url = models.TextField(null=True)

mediaanalytics/forms.py
from django import forms

class SearchForm(forms.Form):
    keyword = forms.CharField(label='Search here', required=False)

mediaanalytics/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Q, Count

from django.contrib import messages

from .models import *
from .api import *

# View for displaying the home page
@csrf_exempt
def home(request):
    context = {}
    context["years"] = yearRange()
    context["sections"] = Article.objects.raw('SELECT 1 as id, section FROM mediaanalytics_article GROUP by section ORDER by section')
    context["authors"] = Article.objects.raw('SELECT 1 as id, author FROM mediaanalytics_article GROUP by author ORDER by author')
    return render(request, 'sitepages/home.html', context)

# View for displaying the graph page
@csrf_exempt
def timeline(request):
    context = {}
    context["years"] = yearRange()
    if request.method == 'POST':
        if request.POST.get("word") != "":
            headerText = ""
            listInput = convertToList(request.POST.get("word"))
            year1 = request.POST.get("year1")
            year2 = request.POST.get("year2")
            # If the user selects both years from the timeline page it would display the timeline for the years in between
            if year1 !="" and year2 !="":
                if int(year1) > int(year2):
                    year1, year2 = year2, year1
                context['year1'] = year1
                context['year2'] = year2
            elif year1 !="":
                context['year1'] = year1
                context['year2'] = yearEnd
            elif year2 !="":
                context['year1'] = yearStart
                context['year2'] = year2
            else:
                #Otherwise it would display the years from yearStart and yearEnd from the loadModels.py file
                context['year1'] = yearStart
                context['year2'] = yearEnd
            if len(listInput) == 1:
                if context['year1']==context['year2']:
                    headerText = "<small>Time series of </small> "+ request.POST.get("word") +" <small>in</small> "+ str(context['year1'])
                else:
                    headerText = "<small>Time series of </small> "+ request.POST.get("word") +" <small>between</small> "+ str(context['year1']) +" <small>and</small> " + str(context['year2'])
            else:
                if context['year1']==context['year2']:
                    headerText = "<small>Time series of words in</small>  "+ str(context['year1'])
                else:
                    headerText = "<small>Time series of words between</small>  "+ str(context['year1']) +" <small>and</small> " + str(context['year2'])
            context['headerText'] = headerText
            if len(listInput) == 1:
                context['word'] = listInput[0]
                return render(request, 'sitepages/timeline/output.html', context)
            else:
                context['words'] = listInput
                return render(request, 'sitepages/timeline/output2.html', context)
    return render(request, 'sitepages/timeline/search.html', context)

# View for displaying the output page
@csrf_exempt
def output(request):
    context = {}
    # Fetches all the articles from the model
    articles = Article.objects.all()
    context['headerText'] = "All articles "
    #If the request is POST
    if request.method == 'POST':
        # If the articleText request is not blank it filters the text to the articles text
        if request.POST.get("articleText") != "":
            articles = articles.filter(Q(text__contains=request.POST['articleText']) | Q(title__contains=request.POST['articleText']))
            context['headerText'] = "Results for " + request.POST.get("articleText")
        # If the year is selected not empty, it filters the date by the year selected
        if request.POST.get("year") != "":
            articles = articles.filter(date__year=request.POST.get("year"))
            context['headerText'] += " in " + request.POST.get("year")
        if request.POST.get("author") != "":
            articles = articles.filter(author=request.POST.get("author"))
            context['headerText'] += " by " + request.POST.get("author")
        if request.POST.get("section") != "":
            articles = articles.filter(section=request.POST.get("section"))
            context['headerText'] += " that are " + request.POST.get("section")

    # Sets the articles context to the articles model
    context['articles'] = articles
    return render(request, 'sitepages/output.html', context)  

# View for displaying the display article page
def display(request, article_id):
    context = {}
    article = get_object_or_404(Article, id=article_id)
    context['article'] = article
    return render(request, 'sitepages/article.html', context)

@csrf_exempt
def nlp(request):
    context = {}
    context["years"] = yearRange()
    if request.method == 'POST':
        # If the first year is not selected it returns back to the NLP home page
        if request.POST.get("year1") !="":
            emptyFields = True
            # GETS ALL THE INFORMATION FROM THE NLP SEARCH PAGE (nlp/search.html)
            context["year1"] = request.POST.get("year1")
            # If the first year is not selected it returns back to the NLP home page
            if request.POST.get("topWordsBreak") !="":
                if request.POST.get("topWordsBreak").isdigit():
                    emptyFields = False
                    context["topWordsBreak"] = request.POST.get("topWordsBreak")
                else:
                    messages.error(request, "ERROR: Top words must be a numeric value")
                    return redirect('mediaanalytics:nlp')
            if request.POST.get("oddOneOut") !="":
                emptyFields = False
                context["oddOneOut"] = request.POST.get("oddOneOut")
            if request.POST.get("ranking") !="":
                emptyFields = False
                context["ranking"] = request.POST.get("ranking")
            if request.POST.get("year2") !="":
                context["year2"] = request.POST.get("year2")
                if int(context["year2"]) == int(context["year1"]):
                    context["year2"] = None
            if request.POST.get("similarWord1") !="" and request.POST.get("similarWord2") !="":
                emptyFields = False
                context["similarity1"] = request.POST.get("similarWord1")
                context["similarity2"] = request.POST.get("similarWord2")
            if request.POST.get("similarWord") !="":
                emptyFields = False
                context["similarWord"] = request.POST.get("similarWord")
            if request.POST.get("ranking") !="":
                emptyFields = False
                context["ranking"] = request.POST.get("ranking")
            if request.POST.get("analogy-x") !="" and request.POST.get("analogy-y") !="" and request.POST.get("analogy-z") !="":
                emptyFields = False
                context["analogyX"] = request.POST.get("analogy-x")
                context["analogyY"] = request.POST.get("analogy-y")
                context["analogyZ"] = request.POST.get("analogy-z")
            if request.POST.get("tnse") !="":
                emptyFields = False
                context["tnse"] = request.POST.get("tnse")
            if emptyFields == True:
                messages.error(request, "ERROR: Must select something below")
                return redirect('mediaanalytics:nlp')
            return render(request, 'sitepages/nlp/output.html', context)
        else:
            messages.error(request, "ERROR: Must select a year")
            return redirect('mediaanalytics:nlp')
    return render(request, 'sitepages/nlp/search.html', context)

def about(request):
    return render(request, 'sitepages/about.html')

# Function that returns the year array from yearStart and yearEnd from the loadModels.py file
def yearRange():
    yearsArray = []
    for i in range(yearStart, yearEnd+1):
        yearsArray.append(i)
    return yearsArray

mediaanalytics/templates/sitepages/about.html
{% extends "layout.html" %}
{% block title %}About Media Analytics{% endblock %}
{% block content %} 
<h1 class="my-4"><a href="{% url 'mediaanalytics:home' %}">Media Analytics</a></h1>
<p>A site that allows anyone to query a large corpus of journalistic data using natural language processing tools. The tool allows for tracking the frequency of word usage over time in the New York Times data corpus as well as querying of word vectors, vector representations of words that capture the semantic loadings of words as well as their semantic changes over time.</p>

<h2 class="my-4"><a href="{% url 'mediaanalytics:timeline' %}">Timeline</a></h2>
Compares the frequency of the word used between two years (e.g. if user selects 1975 to 2017, it would return a time series graph of frequencies for 1975, 1976, 1977...... 2017)

<h2 class="my-4"><a href="{% url 'mediaanalytics:nlp' %}">NLP</a></h2>

<h3>Most similar word</h3>
<p>Which word from the given list doesn’t go with the others according to the selected model? This is computed by calculating the word furthest away from the mean word embedding of all input words. Example: the word out of place in the following list [breakfast, cereal, dinner, lunch] is cereal.</p>

<h3>Similarity between two words</h3>
<p>Computes the cosine similarity between the 2 input words using the word2vec model trained on the selected corpus.</p>

<h3>TSNE visualisation</h3>
<p>Word embeddings (aka word vectors) inhabit a high dimensional space, in the corpuses case, a 300 dimensional space. It is impossible for humans to visualize unassisted the geometrical structure of such a multidimensional data set. The t-SNE algorithm takes a set of points in a high dimensional space and tries to find a faithful representation of those points in a lower dimensional space, typically in the 2D plane. Its objective function tries to map each high dimensional vector into 2 or 3 dimensional representation such that with high probability, similar objects in the high dimensional space are modelled by nearby points in the low dimensional space and dissimilar objects are modelled by distant points.</p>

<h3>Analogical reasoning</h3>
<p>An important property of word embeddings is that the learned word representations capture meaningful syntactic and semantic regularities between words, such as for instance gender or verb tense, and that said regularities are consistent across the vector space. The regularities are observed as constant vector offsets between pairs of words sharing a particular relationship. This property permits the usage of analogical reasoning to answer questions such as “man is to woman as king is to…” by using vector algebra of the form: v_woman-v_man+v_king (where v_n stands for the vector representation of word n). In a properly trained word embedding model with a sufficient and relevant text corpus, the result of the previous vector algebra operation will be a vector whose closest neighbor is the vector for the word “queen”.</p>

<h3>Odd one out</h3>
<p>Which word from the given list doesn’t go with the others according to the selected model? This is computed by calculating the word furthest away from the mean word embedding of all input words. Example: the word out of place in the following list [breakfast, cereal, dinner, lunch] is cereal.</p>

<h3>Show ranking of specific word</h3>
<p>Rank of the word in the frequency ranking of the selected year.</p>

<h3>Show top words</h3>
<p>Retrieve the top-n most frequent words in the selected year.</p>

<footer class="page-footer font-small blue">

  <div class="footer-copyright text-center py-3">Website by Raymond Hua - <a href="http://raymondhua.github.io">raymondhua.github.io</a><br>
  Data scraping by Fawaz Dinnunhan<br>
  Client: David Rozado - <a href="http://drozardo.github.io">drozado.github.io</a><br>
  </div>

</footer>

{% endblock %}

mediaanalytics/templates/sitepages/article.html
{% extends "layout.html" %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %} 
<div class="my-4 article">
	<p><h1>{{ article.title }}</h1></p>
	<p><td>By {{ article.author }}</a></td></p>
	<p><td>{{ article.date }} | {{ article.section }}</td></p>
	<p><td>{{ article.text|safe }}</td></p>
	<p><i>URL: <a href="{{ article.url }}">{{ article.url }}</a><i></p>
</div>
{% endblock %}

mediaanalytics/templates/sitepages/home.html
{% extends "layout.html" %}
{% block content %} 
<div class="my-4 search">
	<h1 class="my-4">Search articles</h1>
	<form action="{% url 'mediaanalytics:output' %}" method=post class=add-entry>

	<div class="row">
		<div class="col-lg-6 col-sm-6 portfolio-item">
			<div class="card card-block">
				<div class="card-body">
					<h4 class="card-title">
						Search here
			    	</h4>
					<input type="text" name="articleText" class="colwidth shadow" placeholder="Leave blank for a result of all articles">
				</div>
			</div>
		</div>

		<div class="col-lg-6 col-sm-6 portfolio-item">
			<div class="card h-100">
				<div class="card-body">
					<h4 class="card-title">Advanced</h4>
				<select name="year" class="colwidthThirty shadow">
					<option value="">All years</option>
					{% for year in years %}
					<option value="{{ year }}">{{ year }}</option>
					{% endfor %}
				</select>
				<select name="section" class="colwidthThirty shadow">
					<option value="">All sections</option>
					{% for section in sections %}
					<option value="{{ section.section }}">{{ section.section }}</option>
					{% endfor %}
				</select>
				<select name="author" class="colwidthThirty shadow">
					<option value="">All authors</option>
					{% for author in authors %}
					<option value="{{ author.author }}">{{ author.author }}</option>
					{% endfor %}
				</select>
				</div>
				</div>
			</div>
		</div>
    <input type="submit" class="button" value="Search" name="submitWord">
	</form>
</div>
{% endblock %}

mediaanalytics/templates/sitepages/output.html
{% extends "layout.html" %}
{% block title %}{{ headerText }}{% endblock %}
{% block content %} 
{% if articles.count > 0 %}
<h1 class="my-4">{{ headerText }}</h1>
<div class="row">
	{% for article in articles %}
	<div class="col-lg-4 col-sm-6 portfolio-item">
		<div class="card h-100">
			<div class="card-body">
				<p class="card-text">{{ article.date }}</p>
				<h4 class="card-title">
				<a class="textColor" href="{% url 'mediaanalytics:article' article.id %}">{{ article.title|slice:":100" }}</a>
				</h4>
				<p class="card-text">By {{ article.author }}</p>
				<p class="card-text">{{ article.section }}</p>
			</div>
		</div>
	</div>
		{% endfor %}
	</div>
<p>{{ articles.count }} article(s) displayed<p>
{% else %}
<p>No articles found<p>
{% endif %}
{% endblock %}