masite/urls.py
from django.contrib import admin
from django.urls import include, path

from mediaanalytics import errorViews
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mediaanalytics.urls')),
    path('admin/', admin.site.urls),
]
handler404 = errorViews.error404
handler500 = errorViews.error500

mediaanalytics/urls.py
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'mediaanalytics'
urlpatterns = [
    # Views URLS
    path('', views.home, name='home'),
    path('article/', views.output, name='output'),
    path('timeline/', views.timeline, name='timeline'),
    path('nlp/', views.nlp, name='nlp'),
    path('about/', views.about, name='about'),
    path('article/<int:article_id>/', views.display, name='article'),
    
    # API URLS
    # POST requests
    path('api/articles/find/', views.getOvertime, name='articlesAPI'),
    path('api/articles/topwords/', views.getTopWords, name='getTopWords'),
    path('api/articles/similar/', views.getSimilarWords, name='getSimilarWords'),
    path('api/articles/notmatch/', views.getNotMatch, name='getNotMatch'),
    path('api/articles/similarity/', views.getSimilarity, name='getSimilarity'),
    path('api/articles/word/', views.getSpecificWord, name='getSpecificWord'),
    path('api/articles/xyz/', views.getAnalogies, name='getAnalogies'),
    # GET requests
    path('api/articles/find/<int:year1>/<int:year2>/<str:word>/', views.getOvertime, name='articlesAPI'),
    path('api/articles/similar/<int:yearID>/<str:wordToFind>/', views.getSimilarWords, name='getSimilarWords'),
    path('api/articles/topwords/<int:yearID>/', views.getTopWords, name='getTopWords'),
    path('api/articles/topwords/<int:yearID>/<int:breakID>/', views.getTopWords, name='getTopWords'),
    path('api/articles/similarity/<int:yearID>/<str:word1>/<str:word2>/', views.getSimilarity, name='getSimilarity'),
    path('api/articles/word/<int:yearID>/<str:word>/', views.getSpecificWord, name='getSpecificWord'),
    path('img/tsne/<int:yearID>/<str:words>/', views.getTSNE, name='getTSNE')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mediaanalytics/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.TextField(null=True)
    text = models.TextField(null=True)
    author = models.TextField(null=True)
    date = models.DateField(null=True)
    section = models.TextField(null=True)
    url = models.TextField(null=True)

mediaanalytics/forms.py
from django import forms

class SearchForm(forms.Form):
    keyword = forms.CharField(label='Search here', required=False)

mediaanalytics/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Q, Count

from django.contrib import messages

from .models import *
from .api import *

# View for displaying the home page
@csrf_exempt
def home(request):
    context = {}
    context["years"] = yearRange()
    context["sections"] = Article.objects.raw('SELECT 1 as id, section FROM mediaanalytics_article GROUP by section ORDER by section')
    context["authors"] = Article.objects.raw('SELECT 1 as id, author FROM mediaanalytics_article GROUP by author ORDER by author')
    return render(request, 'sitepages/home.html', context)

# View for displaying the graph page
@csrf_exempt
def timeline(request):
    context = {}
    context["years"] = yearRange()
    if request.method == 'POST':
        if request.POST.get("word") != "":
            headerText = ""
            listInput = convertToList(request.POST.get("word"))
            year1 = request.POST.get("year1")
            year2 = request.POST.get("year2")
            # If the user selects both years from the timeline page it would display the timeline for the years in between
            if year1 !="" and year2 !="":
                if int(year1) > int(year2):
                    year1, year2 = year2, year1
                context['year1'] = year1
                context['year2'] = year2
            elif year1 !="":
                context['year1'] = year1
                context['year2'] = yearEnd
            elif year2 !="":
                context['year1'] = yearStart
                context['year2'] = year2
            else:
                #Otherwise it would display the years from yearStart and yearEnd from the loadModels.py file
                context['year1'] = yearStart
                context['year2'] = yearEnd
            if len(listInput) == 1:
                if context['year1']==context['year2']:
                    headerText = "<small>Time series of </small> "+ request.POST.get("word") +" <small>in</small> "+ str(context['year1'])
                else:
                    headerText = "<small>Time series of </small> "+ request.POST.get("word") +" <small>between</small> "+ str(context['year1']) +" <small>and</small> " + str(context['year2'])
            else:
                if context['year1']==context['year2']:
                    headerText = "<small>Time series of words in</small>  "+ str(context['year1'])
                else:
                    headerText = "<small>Time series of words between</small>  "+ str(context['year1']) +" <small>and</small> " + str(context['year2'])
            context['headerText'] = headerText
            if len(listInput) == 1:
                context['word'] = listInput[0]
                return render(request, 'sitepages/timeline/output.html', context)
            else:
                context['words'] = listInput
                return render(request, 'sitepages/timeline/output2.html', context)
    return render(request, 'sitepages/timeline/search.html', context)

# View for displaying the output page
@csrf_exempt
def output(request):
    context = {}
    # Fetches all the articles from the model
    articles = Article.objects.all()
    context['headerText'] = "All articles "
    #If the request is POST
    if request.method == 'POST':
        # If the articleText request is not blank it filters the text to the articles text
        if request.POST.get("articleText") != "":
            articles = articles.filter(Q(text__contains=request.POST['articleText']) | Q(title__contains=request.POST['articleText']))
            context['headerText'] = "Results for " + request.POST.get("articleText")
        # If the year is selected not empty, it filters the date by the year selected
        if request.POST.get("year") != "":
            articles = articles.filter(date__year=request.POST.get("year"))
            context['headerText'] += " in " + request.POST.get("year")
        if request.POST.get("author") != "":
            articles = articles.filter(author=request.POST.get("author"))
            context['headerText'] += " by " + request.POST.get("author")
        if request.POST.get("section") != "":
            articles = articles.filter(section=request.POST.get("section"))
            context['headerText'] += " that are " + request.POST.get("section")

    # Sets the articles context to the articles model
    context['articles'] = articles
    return render(request, 'sitepages/output.html', context)  

# View for displaying the display article page
def display(request, article_id):
    context = {}
    article = get_object_or_404(Article, id=article_id)
    context['article'] = article
    return render(request, 'sitepages/article.html', context)

@csrf_exempt
def nlp(request):
    context = {}
    context["years"] = yearRange()
    if request.method == 'POST':
        # If the first year is not selected it returns back to the NLP home page
        if request.POST.get("year1") !="":
            emptyFields = True
            # GETS ALL THE INFORMATION FROM THE NLP SEARCH PAGE (nlp/search.html)
            context["year1"] = request.POST.get("year1")
            # If the first year is not selected it returns back to the NLP home page
            if request.POST.get("topWordsBreak") !="":
                if request.POST.get("topWordsBreak").isdigit():
                    emptyFields = False
                    context["topWordsBreak"] = request.POST.get("topWordsBreak")
                else:
                    messages.error(request, "ERROR: Top words must be a numeric value")
                    return redirect('mediaanalytics:nlp')
            if request.POST.get("oddOneOut") !="":
                emptyFields = False
                context["oddOneOut"] = request.POST.get("oddOneOut")
            if request.POST.get("ranking") !="":
                emptyFields = False
                context["ranking"] = request.POST.get("ranking")
            if request.POST.get("year2") !="":
                context["year2"] = request.POST.get("year2")
                if int(context["year2"]) == int(context["year1"]):
                    context["year2"] = None
            if request.POST.get("similarWord1") !="" and request.POST.get("similarWord2") !="":
                emptyFields = False
                context["similarity1"] = request.POST.get("similarWord1")
                context["similarity2"] = request.POST.get("similarWord2")
            if request.POST.get("similarWord") !="":
                emptyFields = False
                context["similarWord"] = request.POST.get("similarWord")
            if request.POST.get("ranking") !="":
                emptyFields = False
                context["ranking"] = request.POST.get("ranking")
            if request.POST.get("analogy-x") !="" and request.POST.get("analogy-y") !="" and request.POST.get("analogy-z") !="":
                emptyFields = False
                context["analogyX"] = request.POST.get("analogy-x")
                context["analogyY"] = request.POST.get("analogy-y")
                context["analogyZ"] = request.POST.get("analogy-z")
            if request.POST.get("tnse") !="":
                emptyFields = False
                context["tnse"] = request.POST.get("tnse")
            if emptyFields == True:
                messages.error(request, "ERROR: Must select something below")
                return redirect('mediaanalytics:nlp')
            return render(request, 'sitepages/nlp/output.html', context)
        else:
            messages.error(request, "ERROR: Must select a year")
            return redirect('mediaanalytics:nlp')
    return render(request, 'sitepages/nlp/search.html', context)

def about(request):
    return render(request, 'sitepages/about.html')

# Function that returns the year array from yearStart and yearEnd from the loadModels.py file
def yearRange():
    yearsArray = []
    for i in range(yearStart, yearEnd+1):
        yearsArray.append(i)
    return yearsArray

mediaanalytics/templates/sitepages/nlp/footer.html
<footer class="page-footer font-small blue">

  <div class="footer-copyright text-center py-3">By Raymond Hua and David Rozado based on the <a href="http://nlp.op-bit.nz/">NLP site by Tom Paine</a><br>
  </div>

</footer>

mediaanalytics/templates/sitepages/nlp/output.html
{% extends "layout.html" %}
{% load static %}
{% block title %}NLP Results{% endblock %}
{% block content %} 
<script src="{% static 'js/nlp.js'%}"></script>

<div class="row">
    {% if year2 == None %}
	<div class="col-lg-7 col-sm-6 portfolio-item">
    {% else %}
    <div class="col-lg-6 col-sm-6 portfolio-item">
    {% endif %}
		<div class="card h-100">
		    <div class="card-body">
                <h4 class="card-title">
				<p>{{year1}}</p>
			    </h4>
                {% if not similarWord == None %}
                <p></p>
                <h5 id="similarWordsHeader1"></h5>
                <table id="similarWordsTable1">
                </table>
                <script>
                var context = {word: "{{similarWord}}", year: "{{year1}}" };
                $.post("{% url 'mediaanalytics:getSimilarWords' %}", context, function(response) {
                    document.getElementById("similarWordsHeader1").innerHTML = "Similar words to {{similarWord}}";
                    var api = response.similarWords;
                    var tableName = "similarWordsTable1";
                    similarWords(api, tableName);
                });
                </script>
                {% endif %}
                {% if not similarity1 == None %}
                <p></p>
                <h5 id="similarityHeader1"></h5>
                <table id="similarityTable1">
                </table>
                <script>
                var context = {word1: "{{similarity1}}", word2: "{{similarity2}}", year: "{{year1}}" };
                $.post("{% url 'mediaanalytics:getSimilarity' %}", context, function(response) {
                    document.getElementById("similarityHeader1").innerHTML = "Similarity between {{similarity1}} and {{similarity2}}";
                    var api = response.similarity;
                    var tableName = "similarityTable1";
                    similarity(api, tableName);
                });
                </script>
                {% endif %}
                {% if not tnse == None %}
                <p></p>
                <h5 id="tsneHeader1"></h5>
                <canvas id="tsneCanvas1" width="500" height="500"></canvas>
                <script>
                var canvas = document.getElementById("tsneCanvas1");
                var imageLink = "{% url 'mediaanalytics:getTSNE' year1 tnse %}";
                loadTSNEImage(canvas, imageLink, "tsneHeader1", "TSNE for {{tnse}}");
                </script>
                {% endif %}
                {% if not analogyX == None %}
                <p></p>
                <h5 id="analogyHeader1"></h5>
                <table id="analogyTable1">
                </table>
                <script>
                var context = {x: "{{analogyX}}", y: "{{analogyY}}", z: "{{analogyZ}}", year: "{{year1}}" };
                $.post("{% url 'mediaanalytics:getAnalogies' %}", context, function(response) {
                    document.getElementById("analogyHeader1").innerHTML = "Analogies";
                    var api = response.similarWords;
                    var tableName = "analogyTable1";
                    analogy(api, tableName);
                });
                </script>
                {% endif %}
                {% if not oddOneOut == None %}
                <p></p>
                <h5 id="notMatchHeader1"></h5>
                <table id="notMatchTable1">
                </table>
                <script>
                var context = {word: "{{oddOneOut}}", year: "{{year1}}" };
                $.post("{% url 'mediaanalytics:getNotMatch' %}", context, function(response) {
                    document.getElementById("notMatchHeader1").innerHTML = "What word doesn't match from the rest";
                    var api = response.notMatch;
                    var tableName = "notMatchTable1";
                    notMatch(api, tableName);
                });
                </script>
                {% endif %}
                {% if not ranking == None %}
                <p></p>
                <h5 id="rankingHeader1"></h5>
                <table id="rankingTable1">
                </table>
                <script>
                var context = {word: "{{ranking}}", year: "{{year1}}" };
                $.post("{% url 'mediaanalytics:getSpecificWord' %}", context, function(response) {
                    document.getElementById("rankingHeader1").innerHTML = "Details for {{ranking}}";
                    var api = response.word;
                    var tableName = "rankingTable1";
                    specificWord(api, tableName);
                });
                </script>
                {% endif %}
                {% if not topWordsBreak == None %}
                <p></p>
                <h5 id="topWordsHeader1"></h5>
                <table id="topWordsTable1">
                </table>
                <script>
                $.get("{% url 'mediaanalytics:getTopWords' year1 topWordsBreak %}", function(response) {
                    document.getElementById("topWordsHeader1").innerHTML = "Top {{topWordsBreak}} frequent words in {{year1}}";
                    var api = response.topWords;
                    var tableName = "topWordsTable1";
                    topWords(api, tableName);
                });
                </script>
                {% endif %}
			</div>
		</div>
	</div>
    {% if not year2 == None %}
    <div class="col-lg-6 col-sm-6 portfolio-item">
		<div class="card h-100">
		    <div class="card-body">
                <h4 class="card-title">
				<p>{{year2}}</p>
			    </h4>
                {% if not similarWord == None %}
                <p></p>
                <h5 id="similarWordsHeader2"></h5>
                <table id="similarWordsTable2">
                </table>
                <script>
                var context = {word: "{{similarWord}}", year: "{{year2}}" };
                $.post("{% url 'mediaanalytics:getSimilarWords' %}", context, function(response) {
                    document.getElementById("similarWordsHeader2").innerHTML = "Similar words to {{similarWord}}";
                    var api = response.similarWords;
                    var tableName = "similarWordsTable2";
                    similarWords(api, tableName);
                });
                </script>
                {% endif %}
                {% if not similarity2 == None %}
                <p></p>
                <h5 id="similarityHeader2"></h5>
                <table id="similarityTable2">
                </table>
                <script>
                var context = {word1: "{{similarity1}}", word2: "{{similarity2}}", year: "{{year2}}" };
                $.post("{% url 'mediaanalytics:getSimilarity' %}", context, function(response) {
                    document.getElementById("similarityHeader2").innerHTML = "Similarity between {{similarity1}} and {{similarity2}}";
                    var api = response.similarity;
                    var tableName = "similarityTable2";
                    similarity(api, tableName);
                });
                </script>
                {% endif %}
                {% if not tnse == None %}
                <p></p>
                <h5 id="tsneHeader2"></h5>
                <canvas id="tsneCanvas2" width="500" height="500"></canvas>
                <script>
                var canvas = document.getElementById("tsneCanvas2");
                var imageLink = "{% url 'mediaanalytics:getTSNE' year2 tnse %}";
                loadTSNEImage(canvas, imageLink, "tsneHeader2", "TSNE for {{tnse}}");
                </script>
                {% endif %}
                {% if not analogyX == None %}
                <p></p>
                <h5 id="analogyHeader2"></h5>
                <table id="analogyTable2">
                </table>
                <script>
                var context = {x: "{{analogyX}}", y: "{{analogyY}}", z: "{{analogyZ}}", year: "{{year2}}" };
                $.post("{% url 'mediaanalytics:getAnalogies' %}", context, function(response) {
                    document.getElementById("analogyHeader2").innerHTML = "Analogies";
                    var api = response.similarWords;
                    var tableName = "analogyTable2";
                    analogy(api, tableName);
                });
                </script>
                {% endif %}
                {% if not oddOneOut == None %}
                <p></p>
                <h5 id="notMatchHeader2"></h5>
                <table id="notMatchTable2">
                </table>
                <script>
                var context = {word: "{{oddOneOut}}", year: "{{year2}}" };
                $.post("{% url 'mediaanalytics:getNotMatch' %}", context, function(response) {
                    document.getElementById("notMatchHeader2").innerHTML = "What word doesn't match from the rest";
                    var api = response.notMatch;
                    var tableName = "notMatchTable2";
                    notMatch(api, tableName);
                });
                </script>
                {% endif %}
                {% if not ranking == None %}
                <p></p>
                <h5 id="rankingHeader2"></h5>
                <table id="rankingTable2">
                </table>
                <script>
                var context = {word: "{{ranking}}", year: "{{year2}}" };
                $.post("{% url 'mediaanalytics:getSpecificWord' %}", context, function(response) {
                    document.getElementById("rankingHeader2").innerHTML = "Details for {{ranking}}";
                    var api = response.word;
                    var tableName = "rankingTable2";
                    specificWord(api, tableName);
                });
                </script>
                {% endif %}
                {% if not topWordsBreak == None %}
                <p></p>
                <h5 id="topWordsHeader2"></h5>
                <table id="topWordsTable2">
                </table>
                <script>
                $.get("{% url 'mediaanalytics:getTopWords' year2 topWordsBreak %}", function(response) {
                    document.getElementById("topWordsHeader2").innerHTML = "Top {{topWordsBreak}} frequent words in {{year2}}";
                    var api = response.topWords;
                    var tableName = "topWordsTable2";
                    topWords(api, tableName);
                });
                </script>
                {% endif %}
			</div>
		</div>
	</div>
    {% endif %}
</div>

{% include "sitepages/nlp/footer.html" %}

{% endblock %}

mediaanalytics/templates/sitepages/nlp/search.html
{% extends "layout.html" %}
{% block title %}NLP{% endblock %}
{% block content %} 
<div class="my-4 search">
    <h1>NLP</h1>
	<form action="{% url 'mediaanalytics:nlp' %}" method=post class=add-entry>
    {% if messages %}
    {% for message in messages %}
    <label{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</label><br>
    {% endfor %}
    {% endif %}
    <select name="year1" class="colwidthTwentyFive shadow" required>
        <option value="">Select year</option>
        {% for year in years %}
        <option value="{{ year }}">{{ year }}</option>
	    {% endfor %}
    </select>
    <select name="year2" class="colwidthTwentyFive shadow">
        <option value="">Select year to compare (optional)</option>
        {% for year in years %}
        <option value="{{ year }}">{{ year }}</option>
	    {% endfor %}
    </select>
    <br>
	<input type="text" class="colwidthTwentyFive shadow" name="similarWord" placeholder="Enter a word for similar words">
    <br>
    <input type="text" class="borderBox shadow" name="similarWord1" placeholder="Enter first word">
    <input type="text" class="borderBox shadow" name="similarWord2" placeholder="Enter second word">
    <br>
    <input type="text" class="colwidth shadow" name="tnse" placeholder="Enter words for TSNE to visualise. Seperate words by comma">
    <br>
    <input type="text" class="borderBox shadow" name="analogy-x" placeholder="X"> <b>:</b>
    <input type="text" class="borderBox shadow" name="analogy-y" placeholder="Y"> <b>::</b>
    <input type="text" class="borderBox shadow" name="analogy-z" placeholder="Z"> <b>:</b>
    <input type="text" class="borderBox shadow" disabled="" placeholder="?">
    <br>
    <input type="text" class="colwidth shadow" name="oddOneOut" placeholder="Enter words to find the odd one out. Separate words by comma">
    <br>
    <input type="text" class="colwidthRanking shadow" name="ranking" placeholder="Show ranking for specific words. Separate words by comma">
    <br>
    <input type="text" class="borderBox shadow" name="topWordsBreak" placeholder="Show top words">
    <br>
    <input type="submit" class="button" value="Search" name="submit">
	</form>
</div>

{% include "sitepages/nlp/footer.html" %}

{% endblock %}